name: Docker Image CI

on:
  push:
#    branches: [ "main" ]
    branches:
      - main
      - feature-branch-01
  pull_request:
#    branches: [ "main" ]
    branches:
      - main
      - feature-branch-01

jobs:
  staging:
    if: github.ref == 'refs/heads/main'
#    if: ${{github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: pull request
      run: echo ${{github.ref}}
  production:
    if: github.ref != 'refs/heads/main'
#    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: echo ${{github.ref}}
