name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  staging:
#    if: github.ref == 'refs/heads/master'
    if: github.event_name != 'pull_request'
runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: pull request
      run: echo staging
  production:
#    if: github.ref != 'refs/heads/master'
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: echo production
